# versin はリファランスを参考に、APIごとに決める。
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
data:
  # ClusterIP のサービス名でいい。
  # スキームはつけない。そもそも http に乗ってない
  # TCP でやっている。
  # docker イメージを見に行って sh ファイルを追うと
  # 変数の定義などはわかる。
  db_host: mysql
  db_user: wordpress
  db_name: wordpress
  root_random_pass: "yes"
