apiVersion: v1
kind: Service
metadata:
  name: wp-clusterip
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: wp-db-stateful
