apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wp-db-stateful
spec:
  serviceName: wp-db-stateful
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          envFrom:
            - configMapRef:
                name: wp-configmap
            - secretRef:
                name: wp-db-auth
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql-vol
            mountPath: /var/lib/mysql
      # initContainers:
      #   - name: alpine
      #     image: alpine
      #     command: ["rm", "-rf", "/data/lost+found"]
      #     volumeMounts:
      #       - name: data-volume
      #         mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
